### ISSUE TITLE
Login modal does not disappear on Cancel on game submission page

### ISSUE THREAD

**Issue by outfrost** [JammerCore/JammerCore#1805] opened 2019-05-05 19:13 UTC
When on a game submission page, e.g. https://ldjam.com/events/ludum-dare/44/magical-resonance, if I click "Login" at the top, and the login modal appears, I cannot seem to make it disappear by clicking "Cancel", nor by clicking on the modal's semi-transparent background. The only way I can close it is by using `Back` in the browser, possibly twice. The issue does not seem to exist on the [home page](https://ldjam.com/).

**Comment by mikekasprzak** [comment] 2022-03-06 04:47
This is an old one that I'm not able to reproduce. Closing for now. Feel free to open again if it returns.

**Closed by mikekasprzak** 2022-03-06 04:47 UTC
