### ISSUE TITLE
Unpublished drafts in main feed

### ISSUE THREAD

**Issue by occultsoftworks** [JammerCore/JammerCore#1772] opened 2018-09-04 20:02 UTC
Minor bug: Something went wrong when the system rolled over from the Review Phase to the Scoring Phase, and I can see people's unpublished drafts.

![somethingwentwrong](https://user-images.githubusercontent.com/28337733/45054753-e37e0700-b05b-11e8-9903-c99f7c9dbdc3.png)

**Comment by mikekasprzak** [comment] 2018-09-04 20:11
This isn't specific to this moment. This is a general bug with the feed.

**Comment by zwrawr** [comment] 2019-06-20 20:06
duplicate of #1407

**Closed** 2022-03-06 05:01 UTC
Labels: duplicate
